zendframework/zend-expressive

doc/book/usage-examples.md
src/Application.php
src/Container/ApplicationFactory.php
test/ApplicationTest.php
test/Container/ApplicationFactoryTest.php

This patch alters the workflow of `Application` to delay registration of the routing middleware until the first call to `route()` (which may be via one of the proxy calls via `__call()`). This allows sculpting a full middleware pipeline with early interceptors and/or piping to subpaths.
Additionally, the `Container\ApplicationFactory` implementation was updated to allow specifying middleware for the pipeline. To accomplish this, it uses a new configuration key, `middleware_pipeline`, with up to two subkeys, `pre_routing` and `post_routing`. Each specifies an ordered array of middleware or services resolving to middleware; `pre_routing` middleware are registered prior to any routing middleware, and `post_routing` afterwards.
Finally, if services names are used for `middleware_pipeline` …

Delay routing middleware registration to allow pipelines

---

composer.json

in composer.json, currently there is no minimum php version requirement yet.

minimum php version requirement in composer.json

---

src/Application.php

Per @Stanimirdim92 in #20, this updates the Application constructor docblock:
- Fixes the typehint and argument name for the first argument to
reference a router instead of the dispatcher (which no longer exists).
- Updatese the description to remove the verbiage about piping the route
middleware, as that's now delayed until first call to `route()`.

Update Application constructor docblock

---

src/Application.php
src/Router/Route.php
test/ApplicationTest.php

- Tests the various exception paths in `Application::route()`
- Updates `Zend\Expressive\Router\Route` to throw component-specific
exceptions.
Per a comment from @samsonasik on #20

Ensure exception paths in Application::route() are tested

---

doc/book/router.aura.md
doc/bookdown.json

Provides documentation around creating your own Aura.Router instance, configuring it, and injecting it into your router instance for zend-expressive. Both programmatic and IoC approaches are detailed.

Provide documentation around injecting Aura.Router

---

src/Application.php
test/ApplicationTest.php

`FinalHandler` allows passing a `ResponseInterface` instance at instantiation. When invoked without an error, it then compares the received response with its original response to determine whether or not to raise a 404; if they are the same, it raises the 404, otherwise, it returns the received response.
`Application` was not passing the response to the `FinalHandler`, which broke this semantic. This patch does the following:
- adds a new optional argument to `getFinalHandler()`, a response instance. If the method creates a `FinalHandler,` it passes that instance to it.
- updates `__invoke()` to pass the response to `getFinalHandler()` if/when it calls that method.

Ensure that FinalHandler gets original response

---

composer.json
doc/book/router.zf2.md
doc/bookdown.json
src/Router/Zf2.php
test/Router/Zf2Test.php

This patch implements a router that consumes `Zend\Mvc\Router\Http\TreeRouteStack` to provide routing capabilities. HTTP method negotiation is kept internal to the zend-expressive implementation, as the ZF2 router does not differentiate between failure to match the path versus the HTTP method.
Matching marshals a zend-http request using [zend-psr7bridge](https://github.com/zendframework/zend-psr7bridge).

Implement a ZF2 router implementation

---

src/Container/ApplicationFactory.php
test/Container/ApplicationFactoryTest.php

`Application::route()` expects an array or null for its third argument, with null (or absence of the argument) mapping to `Route::HTTP_METHOD_ANY`.
`ApplicationFactory` was passing `Route::HTTP_METHOD_ANY` for the argument, which was raising a fatal error.

Allow ApplicationFactory to handle routes for any method

---

doc/book/usage-examples.md
src/Container/ApplicationFactory.php

The documentation, both in the class as well as the formal documentation, was not correct with regards to the `middleware_pipeline` implementation. This patch updates it to properly indicate the structure.

Document middleware_pipeline accurately

---

src/Application.php
test/RouteMiddlewareTest.php

If a 405 occurs, invoke error middleware instead of the next middleware in the series.
(This is *not* done for general routing failure, as that is expected; the next standard middleware in the pipeline will be invoked in that situation, and, if no more middleware is present or none can handle the request, the final handler will report the 404.)

Invoke error middleware for 405 results

---

doc/book/usage-examples.md
src/Container/ApplicationFactory.php
test/Container/ApplicationFactoryTest.php

Prior to this patch, if you specified pipeline middleware as a service name, the closure returned prevented it from being used as error middleware, as the arity was incorrect.
Since we cannot determine if a service is error middleware until after retrieval, this patch adds a new flag to the pipeline middleware specifications, `error`. When `true`, this will cause the closure used for lazy-loading to have the error middleware signature (arity 4).

Allow flagging pipeline middleware as error handlers

---

phpcs.xml
src/Template/ArrayParametersTrait.php
src/Template/Plates.php
src/Template/TemplateInterface.php
src/Template/Twig.php
test/Template/PlatesTest.php
test/Template/TestAsset/plates-null.php
test/Template/TestAsset/twig-null.html
test/Template/TwigTest.php

I'm working on a [phly-mustache](https://github.com/phly/phly_mustache) template renderer, and discovered one area that becomes more difficult, and one that will also come up for zend-view: by typehinting `$params` on `array`, we do not allow for view models of any sort.
This parameter should drop the typehint, while still retaining the default empty array value.
Additionally, we should allow for passing _no_ parameters; the value is currently required.

Less restrictive `$params` for `TemplateInterface`

---

composer.json
src/Container/ErrorHandlerFactory.php
src/Container/Exception/ExceptionInterface.php
src/Container/Exception/InvalidServiceException.php
src/Container/Exception/NotFoundException.php
src/Container/WhoopsFactory.php
src/Container/WhoopsPageHandlerFactory.php
src/ErrorHandler.php

This patch does the following:
- Adds `filp/whoops` as a dependency.
- Creates a new `Zend\Expressive\ErrorHandler` class, which composes a whoops runtime, `PrettyPageHandler` instance, and optionally a template renderer.
- When an exception is encountered, it invokes whoops to handle the exception.
- For other errors or 404 scenarios, if a template is available, it uses the template to present an error page.
- Provides container factories for whoops, the whoops pretty page handler, and the error handler.
TODO
----

Add error handling via Whoops

---

doc/book/error-handling.md
doc/bookdown.json
src/Application.php
src/Container/TemplatedErrorHandlerFactory.php
src/Container/WhoopsErrorHandlerFactory.php
src/Container/WhoopsPageHandlerFactory.php
src/TemplatedErrorHandler.php
src/WhoopsErrorHandler.php
test/Container/TemplatedErrorHandlerFactoryTest.php
test/Container/WhoopsErrorHandlerFactoryTest.php
test/Container/WhoopsFactoryTest.php
test/Container/WhoopsPageHandlerFactoryTest.php
test/TemplatedErrorHandlerTest.php
test/WhoopsErrorHandlerTest.php

This builds off of #60 (which was inadvertantly merged). It adds a `TemplatedErrorHandler`, and renames `ErrorHandler` to `WhoopsErrorHandler`, having it extend the `TemplatedErrorHandler` in order to provide common functionality between the two implementations.
TODO
----

Error Handling feature

---

src/Router/Aura.php
src/Router/FastRoute.php
src/Router/RouterInterface.php
src/Router/Zf2.php
test/Router/AuraRouteTest.php
test/Router/FastRouteTest.php
test/Router/Zf2Test.php

Allow generating URIs based on a given route specification.

Support route assembly

---

src/Router/Aura.php
test/RouteMiddlewareTest.php

For example, I have routes:
```
'routes' => [
[
'path' => '/',
'middleware' => 'Application\HelloWorld',
'allowed_methods' => [ 'GET' ],
],
],
```
and it means, that / is accessible. but when I access /foo, I got 405 method not allowed. I am using default `Application` implementation, that should be Aura route.

404 doesn't work

---

doc/book/router.aura.md
doc/book/router.fast-route.md
doc/book/router.zf2.md
src/Application.php
src/Container/ApplicationFactory.php
test/ApplicationTest.php
test/Container/ApplicationFactoryTest.php

Hi,
I had trouble with figuring out how to set up a separate `/api` middleware pipe.
My system set up:
1. A `root` middleware pipe (Zend\Expressive\Application) with a `home` route `/` serving the layout + assets for a SPA.
2. A `API` middleware pipe (also Zend\Expressive\Application) with a programmatic created router following the [docs](https://github.com/zendframework/zend-expressive/blob/master/doc/book/router.aura.md#programmatic-creation)
This is how my `index.php` initializes the pipes:
```php
$services = new \Zend\ServiceManager\ServiceManager(new \Zend\ServiceManager\Config(require 'config/services.php'));
$app = $services->get('Zend\Expressive\Application');
$cargoBackend = $services->get('cargo.backend');
$app->pipe('/api', $cargoBackend);
$app->run();
```
And this is the …

App does not route by default

---

doc/book/error-handling.md
src/Container/ApplicationFactory.php
src/Container/TemplatedErrorHandlerFactory.php
src/Container/WhoopsErrorHandlerFactory.php
src/Container/WhoopsFactory.php
src/Container/WhoopsPageHandlerFactory.php
test/Container/ApplicationFactoryTest.php
test/Container/TemplatedErrorHandlerFactoryTest.php
test/Container/WhoopsErrorHandlerFactoryTest.php
test/Container/WhoopsFactoryTest.php
test/Container/WhoopsPageHandlerFactoryTest.php

Today we tried to find out what is the most common name to register the application configuration in the container. In ZF2 you find three versions: `Config`, `config` and `configuration`.
The first two equal to the same service name because zend-servicemanager normalizes it. The latter is an alias for `Config`.
Looking at zend-expressive we recognized that it again uses the normalization "feature": 
https://github.com/zendframework/zend-expressive/blob/master/src/Container/ApplicationFactory.php#L188
Note that `Config` is used but the docs give an example with `config` as service name:
https://github.com/zendframework/zend-expressive/blob/master/doc/book/usage-examples.md#hello-world-using-a-configuration-driven-container
So docs + ApplicationFactory will only work as long as you use …

Inconsistent service name for config

---

src/Container/ApplicationFactory.php
test/Container/ApplicationFactoryTest.php

New config key in a route definition: "name"; if present, it will be used to set the route name.

Allow providing route names via configuration

---

src/Template/TemplatePath.php

as `getNamespace()` may be return null.

add null| to docblock to $namespace property

---

src/Router/Aura.php
test/Router/AuraRouteTest.php

```Fatal error: Call to a member function failedMethod() on null in vendor\zendframework\zend-expressive\src\Router\Aura.php on line 156```

Aura\Router error with no get('/') registered

---

doc/book/application.md
doc/book/router/piping.md
src/Application.php
src/Container/ApplicationFactory.php
test/ApplicationTest.php
test/Container/ApplicationFactoryTest.php

Prior to this patch, the ApplicationFactory implemented lazy loading of pipeline middleware. The feature is very useful, as it delays fetching of middleware until execution by wrapping the call to fetch and invoke it in a closure.
This patch pushes that feature into `Application` itself:
- `pipe()` now allows specifying middleware by service name.
- A new method, `pipeErrorHandler()`, proxies to `pipe()`, but wraps lazy-middleware in a wrapper that uses the error middleware signature.
`ApplicationFactory` has been updated to use these facilities, and removes its own. Documentation has been updated to indicate the lazy-middleware features.

Implement middleware lazy-loading

---

README.md
composer.json
doc/book/container/intro.md
doc/book/error-handling.md
doc/book/quick-start.md
doc/book/template/intro.md

Hi, 
As the router and container can be moved what about moving those to require-dev and have a project/skelton repo which comes with service and router by default ?
Else the problem is we install the extra components and will not be using those.
Thank you.

Move router and service to require-dev

---

src/Application.php
src/TemplatedErrorHandler.php
test/ApplicationTest.php
test/Container/ApplicationFactoryTest.php
test/IntegrationTest.php

The Stratigility FinalHandler never calls `create404` because of [this line](https://github.com/zendframework/zend-stratigility/blob/716c647fb76303c76c0c254bb4c5bc628aefa7e1/src/FinalHandler.php#L83). In [getFinalHandler()](https://github.com/zendframework/zend-expressive/blob/23c48d8f770fd73a062b903682bbf6d4aff6918c/src/Application.php#L371) of Expressive the $response will be a Diactoros Response (or other PSR-7), which gets passed to the Final Handler, and then decorated by Stratigility.  The result is the FinalHandler response will **never** equal the invoked response so the $response is returned by the FinalHandler and the 404 is never shown.

404 is never called from FinalHandler

---

doc/book/template/zend-view.md
src/Exception/RenderingException.php
src/Template/ZendView.php
test/Template/TestAsset/zendview-layout.phtml
test/Template/TestAsset/zendview-layout2.phtml
test/Template/ZendViewTest.php

This pull request better abstracts layout capabilities for the zend-view adapter. It does so by:
- Allowing passing a layout script name or ViewModel representing the layout as the second argument in the constructor.
- Allowing passing a "layout" parameter during rendering, which may be a layout script name or a ViewModel representing the layout.
In each case, rendering now munges the provided template and parameters into a view model, injecting it as a child of the layout view model if one is discovered (if a layout script name is passed, a layout view model is created to represent it).
This makes usage look more like the other adapters, and brings its capabilities to the same level of completion.

Abstract layout capabilities in zend-view adapter

---

doc/book/quick-start.md

Without installing the zend-servicemanager, the example code throws an error since AppFactory cannot instantiate the default container.

Update quickstart documentation to install default container

---

doc/book/router/fast-route.md

Fix for PSR-0/4 compliance. Important for those of us who like to copy/paste examples!

Fix example classname in documentation

---

src/Application.php
src/Container/ApplicationFactory.php
test/ApplicationTest.php

It makes sense to compose an EmitterStack by default; that way, users of AppFactory can manipulate the emitter without needing to resort to direct instantiation.

Compose an EmitterStack by default

---

README.md

as currently there is a release, should we update the composer require command in doc to to a version ?

change composer require from *@dev to ~0.* ?

---

doc/book/container/factories.md

This should fix some of the formatting on http://zend-expressive.readthedocs.org/en/latest/container/factories/

Increased indentation of nested bullet points (for RTD)

---

doc/book/template/middleware.md

The data array should be passed to the template renderer, not the response body stream.

Fix typo in templates->render

---

doc/book/usage-examples.md

Looks like a few of the paths were incorrect in the usage-examples.md when using merged config files.
- It appears global.php should be config/autoload/global.php as opposed to config/global.php
- the config service defined in config/autoload/dependencies.global.php points to absolute path __DIR__ . /config.php" which would not exist since config.php is actually in the parent directory.

Updated config path typos.

---

doc/book/template/twig.md

Fixed typo in documentation, since the `TwigTemplate` class does not exist.

Fixed usage of non-existent TwigTemplates class

---

src/Container/ApplicationFactory.php
test/Container/ApplicationFactoryTest.php

When a route instance is created by calling `$app->route(...)`, that instance is automatically added to the router, which tries to process the route options.
The problem is that the `ApplicationFactory` sets the options after that, which makes the router ignore any option defined for the route.
Creating the route as a new `Zend\Expressive\Router\Route` instance and passing it to the `$app->route(...)` method after processing the options fixes this problem.

Route options not processed in ApplicationFactory

---

src/WhoopsErrorHandler.php

There is no error handler pushed. That's why the pages are empty on errors. This fixes #124.

Fix not pushing error handler

---

doc/book/container/factories.md
doc/book/template/intro.md
doc/book/template/zend-view.md
src/Container/Template/PlatesFactory.php
src/Container/Template/TwigFactory.php
src/Container/Template/ZendViewFactory.php
src/Template/Twig/TwigExtension.php
src/Template/ZendView/ServerUrlHelper.php
src/Template/ZendView/UrlHelper.php
test/Container/Template/PathsTrait.php
test/Container/Template/PlatesFactoryTest.php
test/Container/Template/TwigFactoryTest.php
test/Container/Template/ZendViewFactoryTest.php
test/Template/Twig/TwigExtensionTest.php
test/Template/ZendView/ServerUrlHelperTest.php
test/Template/ZendView/UrlHelperTest.php
test/WhoopsErrorHandlerTest.php

This patch aims to address #122 and #123, by providing container factories for each template engine, as well as useful facilities for integrating them with Expressive.

Provide template factories and facilities

---

src/Router/AuraRouter.php
test/Router/AuraRouterTest.php

Expressive is using AuraRouter 2.3.x, however it is not compatible with PSR-7. I'm trying to write tests for a specific route.
```php
$request  = new ServerRequest([], [], 'https://example.com/api/ping', 'GET');
$response = new Response();
$this->app->run($request, $response);
```
Since the GET request method is set with ``new ServerRequest``, I expect the router to use this. However AuraRouter 2.x is looking at ``$_SERVER['REQUEST_METHOD']`` and not the ``$request->getMethod()``. Obviously in the web application accessed through a web server it is working as expected since the $_SERVER is populated there.
https://github.com/auraphp/Aura.Router/blob/2.x/src/Route.php#L424-L435
AuraRouter 3.x seems to be PSR-7 friendly, but they changed some class names and doesn't work out of the box. …

AuraRouter 2.x is not PSR-7 compatible

---

mkdocs.yml
src/Router/AuraRouter.php
src/Router/RouterInterface.php
test/Router/AuraRouterTest.php

As an alternative to #134. The primary issue reported in that pull request was that the author wished to get the raw URL instead of the escaped version.
2 of the 3 implementations we provide do not encode URIs (ZendRouter and FastRoute), and 3rd party utilities such as league/uri provide escaping capabilities at a fine-grained level. As such, this patch updates the interface to specify that implementations MUST NOT encode URIs returned by `generateUri()`. Additionally, the Aura router was updated to call `generateRaw()` internally to comply with the specification.

Specify that `generateUri()` MUST NOT encode returned URIs

---

src/Template/AddParametersTrait.php
src/Template/PlatesRenderer.php
src/Template/TemplateRendererInterface.php
src/Template/TwigRenderer.php
src/Template/ZendViewRenderer.php
test/Template/PlatesRendererTest.php
test/Template/TestAsset/plates-2.php

My first run at #142. Only tried it with Plates so far. There's probably a better way to do this with ZendView, but I'm a little hazy on that. Let me know if I'm on the right track and I'll do the tests and docs.

Adding parameters to templates before render-time

---

CHANGELOG.md
doc/book/router/interface.md
doc/book/router/uri-generation.md
src/AppFactory.php
src/Container/ApplicationFactory.php
src/Router/AuraRouter.php
src/Router/FastRouteRouter.php
src/Router/Route.php
src/Router/RouterInterface.php
src/Router/ZendRouter.php
test/AppFactoryTest.php
test/Container/ApplicationFactoryTest.php
test/Router/AuraRouterTest.php
test/Router/FastRouteRouterTest.php
test/Router/ZendRouterTest.php

Hi,
I don't know where this discussion (https://github.com/zendframework/zend-expressive/issues/131) will bring us, but if we keep one default router, I think it should be FastRoute.
I've tried FastRoute and Aura, and FastRoute is definitely easier to use. See the comparaison:
Aura:
```php
return [
'routes' => [
[
'path' => '/users/:id',
'options' => [
'tokens' => [
'id' => '[0-9]+'
]
],
'middleware' => 'Application\HelloWorld',
'allowed_methods' => [ 'GET' ],
],
],
];
```
FastRoute:
```php
return [
'routes' => [
[
'path' => '/users/{id:[0-9]+}',
'middleware' => 'Application\HelloWorld',
'allowed_methods' => [ 'GET' ],
],
],
];
```
Aura reminds me a bit the verbosity of ZF2. FastRoute allows very compact definitions.
I don't know though if FastRoute lacks some important features that Aura …

Use FastRoute by default

---

src/Application.php
test/ApplicationTest.php
test/Container/ApplicationFactoryTest.php
test/RouteMiddlewareTest.php

Every time the `Container::has` method is internally called, the second argument is set to true, so that when using the Zend\ServiceManager, it includes abstract factories.
Without this, when using the ServiceManager v3, regular middleware, route middleware and any service that is internally fetched and should be created by abstract factories is instantiated instead of being pulled from the Container.

Added second argument to Container::has callas in order to make the ServiceManager to include abstract factories

---

doc/book/container/factories.md
doc/book/quick-start.md

`AppFactory::create()` works with FastRoute by default

Replace Aura router by FastRoute in docs

---

README.md
doc/book/quick-start-skeleton.md
doc/book/quick-start.md
doc/bookdown.json
mkdocs.yml

- Updates the README install instructions to prefer the skeleton app over manual installation.
- Adds a chapter to the docs on getting started with the skeleton application and installer. This chapter also covers some next steps: creating middleware, and using templates.
- Updated the title of the original quickstart to indicate it covers standalone usage.

Updated documentation to cover skeleton application

---

src/Emitter/EmitterStack.php

using InvalidArgumentException from Zend\Expressive\Exception namespace

---

doc/book/quick-start-skeleton.md

Per zendframework/zend-expressive-skeleton#9, this puts the DI definition information in the `routes.global.php` file, in order to keep routing/middleware information in one file.

Put middleware DI info in routes.global.php

---

README.md

I saw this addition on quick start in e325ee6343bb30420afd40073afc001c7dc978d9 but it was not added in README.me as well.

Add `-s rc` flag in README.md

---

doc/book/quick-start-skeleton.md

Without the quotes, produces warning: 
Warning: htmlspecialchars(): charset `-8' not supported, assuming utf-8 in ... on line ...
And then fatal error:
Fatal error: Uncaught exception 'RuntimeException' with message 'Unable to emit response; headers already sent' ...

stringify UTF-8 to fix PHP warning

---

src/Application.php
test/RouteMiddlewareTest.php

On successful routing, inject the route result as the `Zend\Expressive\Router\RouteResult` request attribute. This allows users to introspect it later, allowing for features such as injection into URL helpers or similar.
One part of a multi-part solution addressing #186.

Inject the route result as an attribute

---

src/Template/ArrayParametersTrait.php
test/Template/ArrayParametersTraitTest.php
test/Template/TestAsset/ArrayParameters.php
test/Template/TestAsset/ViewModel.php

Currently, if you use zend-view view models, but decide to switch to an alternate template implementation, you must also change the rest of your code to eliminate the view models (see discussion on [zend-view Expressive renderer repository](https://github.com/zendframework/zend-expressive-zendviewrenderer/issues/2).
This patch introduces the following:
- Tests for the `ArrayParametersTrait::normalizeParams()` implementation.
- Code that uses duck-typing to locate zend-view view models, and, when discovered, return the result of `getVariables()`.
Duck-typing was used so as to eliminate the need for an additional dependency. Hopefully, a future update to zend-view will eliminate the need for this check at all. In the meantime, this allows each of the `Zend\View\Model\ModelInterface` …

Support casting zend-view models to arrays

---

src/Application.php
test/ApplicationTest.php
test/Container/ApplicationFactoryTest.php
test/RouteMiddlewareTest.php

Reverts 117b2195371eb8285bc63c443babc6bb520f58e5
Related:
* https://github.com/zendframework/zend-servicemanager/pull/49
* https://github.com/zendframework/zend-expressive/pull/156

Removed $checkAbstractFactories flag from ServiceManager::has()

---

src/Application.php
test/ApplicationTest.php
test/Container/ApplicationFactoryTest.php
test/Container/TemplatedErrorHandlerFactoryTest.php
test/Container/WhoopsErrorHandlerFactoryTest.php
test/Container/WhoopsFactoryTest.php
test/Container/WhoopsPageHandlerFactoryTest.php
test/ContainerTrait.php
test/RouteMiddlewareTest.php

[test] Add helpers for deal with ContainerInterface mock

---

src/Container/ApplicationFactory.php
src/Container/Exception/InvalidArgumentException.php
test/Container/ApplicationFactoryTest.php

This PR addresses issue #196.
/cc @Maks3w 
Fix #196

Improved exceptions handling within the Container\ApplicationFactory

---

src/Application.php
src/Container/ApplicationFactory.php
src/Router/Route.php
src/Router/RouteResult.php
test/ApplicationTest.php
test/Container/ApplicationFactoryTest.php
test/TestAsset/InvokableMiddleware.php

The ApplicationFactory will check to see if the specified middleware is
an array before injecting it into the Route. If it is, it will attempt
to turn the contents of the array (which must be callable or retrievable
from the DI container) into a MiddlewarePipe, which it will inject
instead.
This change should be backwards compatible unless an application's functionality currently depends on failing if an array is specified in `routes.[].middleware`.
If acceptable, this would resolve #190

Added support for route-specific middleware pipe via configuration

---

doc/book/router/bookdown.json
doc/book/router/result-observers.md
mkdocs.yml
src/Application.php
src/Router/RouteResultObserverInterface.php
test/RouteMiddlewareTest.php

This patch implements a subject/observer for notifying subscribers of a `RouteResult`. The primary use case is for URI generators, which may want access to the calculated `RouteResult`, without needing to resort to injection of middleware.
`update()` was chosen as the observer method, for affinity with [SplObserver](http://php.net/SplObserver).

Implement subject/observer for route result notification

---

doc/book/cookbook.md

@weierophinney this is what I can get from your site: https://github.com/weierophinney/mwop.net/blob/master/config/autoload/global.php . Still not sure about using 404 page with `WhoopsErrorHandler` or `TemplatedErrorHandler`. 
Note:
defining `'error' => true` in `middleware_pipeline` config make it not working. Please let me know if I missed something. Thanks.

added cookbook for set up custom 404 page

---

CHANGELOG.md
doc/book/router/interface.md
src/Router/RouterInterface.php

Per #189, `addRoute()` **MUST** raise a `RuntimeException` if called after either `match()` or `generateUri()` have been called, to ensure the router state does not change between invocations.
Replaces #189.

Clarify that addRoute must raise exception

---

src/Template/ArrayParametersTrait.php
src/Template/DefaultParamsTrait.php
src/Template/Exception/ExceptionInterface.php
src/Template/Exception/InvalidArgumentException.php
test/Template/ArrayParametersTraitTest.php

In preparation for splitting the Template subcomponent into its own repository, this patch:
- adds an `Exception` subcomponent, with an `ExceptionInterface` marker interface and an `InvalidArgumentException` concrete implementation.
- updates the ArrayParametersTrait and DefaultParamsTrait to use the subcomponent-specific exceptions.
- updates the ArrayParametersTrait to test for the subcomponent-specific exceptions instead of the component-level exceptions.

Create subcomponent-specific exceptions for Template subcomponent

---

CHANGELOG.md
doc/book/router/result-observers.md
src/Application.php
src/RouteResultObserverInterface.php
test/RouteMiddlewareTest.php

This patch moves the `RouteResultObserverInterface` into the `Zend\Expressive` namespace. Since it is triggered by `Application`, it is an application-level responsibility, not the router's.
Since the class names do not conflict, this can lead to an immediate deprecation of the original interface in the zend-expressive-router package. However, zend-expressive-zendviewrenderer will need updates so that it fulfills the new interface via its `UrlHelper` instance.
Since the interface has not been part of an official Expressive release yet, this change is backwards compatible.

Moves the RouteResultObserverInterface back to the Expressive namespace

---

doc/book/helpers/bookdown.json
doc/book/helpers/intro.md
doc/book/helpers/server-url-helper.md
doc/book/helpers/url-helper.md
doc/book/router/result-observers.md
doc/bookdown.json
mkdocs.yml

This patch adds a new section on zendframework/zend-expressive-helpers, detailing installation, usage, and configuration of each of the `UrlHelper` and `ServerUrlHelper`.
It also updates the Observers documentation as follows:
- It removes the section on delegator factories; and
- Adds a section detailing how factories for observers can also attach the observer to the application instance, which becomes a portable way of accomplishing the task between container implementations.

Added documentation on zend-expressive-helpers

---

composer.json

Hi,
I've checked and this repo no longer has any dependency with Zend\Stdlib.

Remove Stdlib dependency

---

.travis.yml
CHANGELOG.md
CONTRIBUTING.md
composer.json

- Updated CHANGELOG.
- Updated composer.json:
- Set all router/template dev/suggest dependencies to `^1.0`.
- Updated PHP dep to `^5.5 || ^7.0`
- Added `scripts` section.
- Updated travis.yml:
- use composer scripts for each task.
- Updated CONTRIBUTING:
- Detail using composer scripts for testing, CS checks, vs specific tools.

1.0.0rc3 readiness

---

doc/book/helpers/server-url-helper.md
doc/book/helpers/url-helper.md

This updates the documentation to follow the changes in zend-expressive-helpers 1.2.0 (and upcoming zend-expressive-skeleton 1.0.0rc4). Additionally, it fixes the header levels of the notes in the server-url-helper documentation.

Updated url-helper documentation to 1.2.0

---

doc/book/usage-examples.md

Using code like
return ConfigFactory::fromFiles(
glob('config/autoload/{global,local}.php', GLOB_BRACE)
);
as described in Expressive example for config/config.php does not work on a stack described in the header (see http://zend-expressive.readthedocs.org/en/stable/usage-examples/#hello-world-using-a-configuration-driven-container).
http://www.php.net/function.glob notes: The GLOB_BRACE flag is not available on some non GNU systems, like Solaris. On my system it produces "Catchable fatal error: Argument 2 passed to Zend\Stdlib\ArrayUtils::merge() must be of the type array, integer given..."
Is there a requirement to change examples, or change Zend Config Factory::fromFiles, or change Zend Stdlib ArrayUtils::merge?

GLOB_BRACE fails on Win 7 using Xampp stack

---

doc/book/cookbook.md

I have setup my `Zend\Expressive` application and really like the lightweight approach. But currently I am struggling to set up form view helpers to output a form in a view template. One issue I tracked down is due to the fact, that `Zend\Form` is not fully refactored to use the latest `Zend\ServiceManager` changes. But I am not sure if that is all to fix this.
I found some posts. The first is about integrating with Aura.DI:
http://harikt.com/blog/2015/11/13/integrating-zend-form-in-zend-expressive-and-view/
And the second with `Zend\ServiceManager` (which I could not get to run due to the current incompatibilities mentioned above):
http://www.masterzendframework.com/zend-expressive-enable-form-view-helpers/
It would be nice if the usage of form view helpers could be supported to help …

How to setup form view helpers

---

doc/book/quick-start-skeleton.md

Per zendframework/zend-expressive-skeleton#37, this patch updates the quick start to reference the path `src/App/Action/` instead of `src/Action/`.

Updates paths for App\Action namespace

---

doc/book/quick-start-skeleton.md
doc/book/quick-start.md
doc/book/usage-examples.md

This follows on from zendframework/zend-expressive-skeleton#41, demonstrating how to use the built-in `composer serve` command from the installer, as well as how to create the command in standalone installations.

Document the `composer serve` command

---

doc/book/container/aura-di.md
doc/book/quick-start.md

In the getting started tutorial, this sample code is shown:
```php
$app->get('/', function ($request, $response, $next) {
$response->write('Hello, world!');
return $response;
});
```
I don't think that's valid as the Psr\Http\Message\ResponseInterface has no write() method.
It should be changed to ```$response->getBody()->write('Hello, world!');```
(If the PSR-7 http implementations are Slim's request and response, this can work, as they added this non-PSR-7's method into their Response implementation, but it doesn't seem correct to me as the router's callback expects a response of the type Psr\Http\Message\ResponseInterface, thus we are violating the contract)

Getting started tutorial: no method write() in PSR-7's ResponseInterface

---

README.md
composer.json
doc/book/container/pimple.md

Following on zendframework/zend-expressive-skeleton#49, this patch updates the codebase to recommend xtreamwayz/pimple-container-interop for Pimple users. This is to ensure developers are using the latest stable release of Pimple (currently v3), and using a container with the same public API as Pimple itself.
Fixes #129

Update docs to use xtreamwayz\pimple-container-interop

---

doc/book/cookbook/bookdown.json
doc/book/cookbook/using-a-base-path.md
mkdocs.yml

This patch adds a recipe to the cookbook covering how to serve Expressive applications from subdirectories.
Fixes zendframework/zend-expressive-skeleton#51

Added a recipe for base path resolution

---

doc/book/helpers/body-parse.md

I am not sure if we want to use (BodyParams\)BodyParamsMiddleware as the document heading as it was done with the url helpers (and rename the file accordingly) so i used the title provided in the bookdown.json

class name fixes

---

doc/book/cookbook/bookdown.json
doc/book/cookbook/using-routed-middleware-class-as-controller.md

@weierophinney as your request in [my blog post](https://samsonasik.wordpress.com/2016/01/03/using-routed-middleware-class-as-controller-with-multi-actions-in-expressive/#comment-13694), here we go...

add cookbook for routed middleware class as controller with multi actions

---

README.md
doc/book/quick-start-skeleton.md

Composer installs the dev requirements *as listed before running any scripts* when executing `create-project`. By specifying `--no-dev`, we prevent that from occurring.
This also adds a note that if you want development requirements, you *must* run `composer update` on completion.
See zendframework/zend-expressive-skeleton#60 for details.

use --no-dev flag when installing

---

src/ErrorMiddlewarePipe.php
src/MarshalMiddlewareTrait.php
test/Container/ApplicationFactoryTest.php
test/ErrorMiddlewarePipeTest.php

Given the following middleware specification:
```php
[
'middleware' => [
Unauthorized::class,
Unauthenticated::class,
],
'error' => true,
'priority' => -10000,
]
```
Neither middleware listed triggers. Each will trigger, however, if you do them separately, not as part of a list:
```php
[
'middleware' => Unauthorized::class,
'error' => true,
'priority' => -10000,
],
[
'middleware' => Unauthenticated::class,
'error' => true,
'priority' => -10000,
],
```
The error is because the `MarshalMiddlewareTrait` ~~is not retaining the `error` flag when marshaling lazy middleware services.~~ composes a `MiddlewarePipe` instance when creating an error middleware pipeline, but that class does not implement the error middleware signature.
This patch creates a `Zend\Expressive\ErrorMiddlewarePipe` …

Nested error middleware does not work correctly

---

doc/book/cookbook/setting-locale-depending-routing-parameter.md

Without it fastroute gives "Number of opening '[' and closing ']' does not match" exception

Adding missing ":" character to fastroute multilanguage parameter

---

doc/book/cookbook/using-a-base-path.md

Take advantage of latest release of `mtymek/blast-base-url`, simplifying configuration.
I also released version 0.1 of this package, so there is no need to use dev-master anymore.

Update base path cookbook

---

CHANGELOG.md
src/Container/ApplicationFactory.php

fixes #290
According to phpstorm this updates all references to rtfd.org.

Fix for #290: Update migration links in docs and changelog

---

doc/book/css/zend-expressive.css
mkdocs.yml

- Adds doc/book/css/zend-expressive.css.
- Adds `extra_css` configuration to `mkdocs.yml` to include the above.
This is being done prior to evaluating #297 and completion of merging zendframework/zf-mkdoc-theme#2, to simplify component-specific CSS.

Move component-specific CSS into component

---

doc/book/cookbook/modular-layout.md

Hi,
I'd suggest that we update the wording for better consistency and better reflect the fact that your App (the one merging is config), is mostly merging config of modules / standalone-libraries / non-app code (and not other app).
This better reflect the distinction between an app (which is actually the consuming code), and the reusable-code.

Update naming modular-layout.md

---

.travis.yml

Per zendframework/zf-mkdoc-theme#3, this pull request updates the `.travis.yml`:
- `PATH` is now set in the PHP 5.6 environment, where it will be used; the line was removed from the `before_install` section.
- `DEPLOY_DOCS` is set in the PHP 5.6 environment, based on `TRAVIS_BRANCH` and `TRAVIS_PULL_REQUEST`
- A new line was added to `script` to grab the theme-installer.sh and execute it if `TRAVIS_TEST_RESULT` indicates success.
- `after_success` was simplified to only test for `DEPLOY_DOCS`.

Updated .travis.yml to use zf-mkdoc-theme installer script

---

doc/book/cookbook/flash-messengers.md

Simple typo I noticed while browsing the flash messenger cookbook.

Fix typo in flash-messengers.md

---

composer.json
src/Application.php
test/ApplicationTest.php

As noted in zendframework/zend-diactoros#171, the `ServerRequestFactory::fromGlobals()` method raises exceptions on malformed information, such as:
- malformed file upload data
- invalid HTTP protocol versions
At the application level, we should catch these, and invoke the final handler with a 400 response when caught.
I've opened this against master, as I consider the current behavior a "bug"; however, in a way, it's technically a new feature. I'd appreciate comments as to the preferred release. :smile:

Intercept exceptions from the ServerRequest factory

---

doc/book/features/router/fast-route.md

Tiny Typo, it's [`FastRouteRouter`](https://github.com/zendframework/zend-expressive-fastroute/blob/master/src/FastRouteRouter.php), not `FastRoute`…

fixes FastRouteRouter typo

---

doc/book/reference/usage-examples.md

I'm not sure if the documentation was correct previously, but whenever
I've tried to follow it, to the letter, it's resulted in segmentation
faults and the routes never being loaded. Given that, after some further
research, I believe that the previous recommendation was never going to
work. So, I've migrated some of the configuration from a setup using the
skeleton installer and updated the docs to reflect that.
I don't mean what I've said in any kind of mean or uncharitable way. 
Perhaps the configuration worked up until a particular revision, but was
not updated to reflect subsequent changes. Or, perhaps the fault lies with
me, and I wasn't as thorough as I thought I was. Either way, I offer this for 
consideration and review.

Correct the documentation for configuring a container-driven container

---

README.md
doc/book/getting-started/standalone.md
doc/book/index.md

Updating per [zend-expressive-router@#14](https://github.com/zendframework/zend-expressive-router/pull/14)

Reference zend-router instead of ZF2 MVC in docs

---

src/Container/TemplatedErrorHandlerFactory.php
src/Container/WhoopsErrorHandlerFactory.php

Fix: Use class keyword where possible

---

src/ErrorMiddlewarePipe.php

Fix: Docblock

---

doc/book/cookbook/using-zend-form-view-helpers.md

Updates zend form plugin helper example and removes the deprecated `Zend\Form\View\HelperConfig`.

[docs] Update HelperPluginManagerFactory example

---

doc/book/cookbook/setting-locale-depending-routing-parameter.md

As discussed on IRC and in #350.
This changes how the locale is stored in the cookbook example. Since it's not reliable to use the global static `Locale::setDefault()`, it's better to store it as a request attribute.

[docs] Use locale request attribute in favor of the static global locale

---

.docheader
.travis.yml
composer.json
src/Container/Exception/ExceptionInterface.php
src/Container/Exception/InvalidArgumentException.php
src/Container/Exception/InvalidServiceException.php
src/Container/Exception/NotFoundException.php
src/Exception/BadMethodCallException.php
src/Exception/DuplicateRouteException.php
src/Exception/InvalidArgumentException.php
src/Exception/RuntimeException.php
src/TemplatedErrorHandler.php
src/WhoopsErrorHandler.php

If the tool to check license headers is considered overkill, just tell me, so I can remove it.

Fix license header

---

README.md

Why not display the badge if we already use Coveralls?

Added Coveralls Badge to README

---

composer.json
src/Container/WhoopsErrorHandlerFactory.php
src/Container/WhoopsFactory.php
src/WhoopsErrorHandler.php
test/Container/WhoopsErrorHandlerFactoryTest.php
test/Container/WhoopsFactoryTest.php
test/Container/WhoopsPageHandlerFactoryTest.php
test/WhoopsErrorHandlerTest.php

This PR adds support for Whoops 2.0 as discussed in zendframework/zend-expressive-skeleton#115 and #383.
Falling back to 1.1 is no option since it doesn't support PHP 7.
It's not optimal but it adds support fro 2.0 while maintaining BC.

Add support for Whoops 2.0

---

src/Application.php
test/IntegrationTest.php

Stratigility 1.3 deprecates having an optional `$out` argument to `__invoke()`. However, `Application::run()` was calling without the argument, to allow lazy-creation of a final handler if none was injected at instantiation.
In order to mimic the behavior of `MiddlewarePipe`, this meant testing:
- For a null `$out` argument
- A null return value from `getFinalHandler()`
- Decorating a PSR response with a Stratigility response
- Seeding a Stratigility `FinalHandler` with the decorated response
I removed a condition from an error handler that was checking for deprecations in order to ensure that deprecation notices *were* being emitted previously, and after changes, were not. Interestingly, these were not triggering failures for me locally; I was only seeing the deprecation notices within …

Ensure `Application::__invoke()` does not trigger deprecations

---

src/Application.php
src/TemplatedErrorHandler.php
src/WhoopsErrorHandler.php
test/IntegrationTest.php
test/TemplatedErrorHandlerTest.php
test/WhoopsErrorHandlerTest.php

This patch does the following:
- Updates the `TemplatedErrorHandler` and `WhoopsErrorHandler` to no longer use Stratigility request/response decorator-specific methods. Instead, they now pull values via the `original*` request attributes, using default values.
- Updates the `Application::run()` method to set the `originalResponse` request attribute; this allows the above changes to be used with Stratigility versions prior to 1.3 (which is the first release in which that attribute was introduced).
- Updates the integration test to remove error handling for deprecation notices based on usage of Stratigility request/response decorators, as they are no longer invoked.
Other than the error handling deprecations, this now allows Expressive to run without deprecation notices.

Eliminate deprecation notices due to request/response decorator usage

---

src/Application.php
test/Container/ApplicationFactoryIntegrationTest.php

Users cannot yet set the raiseThrowables flag, as there are not shipped facilities for handling errors using templates or whoops. As such, currently, if the queue is exhausted or an exception is thrown, error middleware is triggered. This patch adds an error handler to `Application::__invoke()` to swallow deprecation notices due to invocation of error middleware.

Prevent deprecation notice based on triggering error middleware

---

src/Application.php
test/IntegrationTest.php

Per #400, when we register a new error handler to swallow deprecation notices in `Application::__invoke()`, if any global error handlers were registered previously, they now disappear.
This patch adds a test covering that scenario, and updates the `Application` class as follows:
- The `set_error_handler()` call in `Application::__invoke()` has been replaced with a call to a new method, `swallowDeprecationNotices()`.
- `swallowDeprecationNotices()` now captures the return value of calling `set_error_handler()`; if that value is non-empty, it creates a new error handler closing over its own error handler and the previous which invokes the previous if our own returns false.
This serves as an alternate solution to #401.

Make PHP error handler operate in a stack

---

.docheader
composer.json
composer.lock
src/AppFactory.php
src/Exception/MissingDependencyException.php

`AppFactory::create` now raises a new `MissingDependencyException` in either of
the two following scenarios:
- `$container` absence, and lack of `ServiceManager`
- `$router` absence, and lack of `Router\FastRouteRouter`
Note: I was unable to write tests, because both classes are always present in our test suite!
Fixes #352

Added handling for missing container/router in AppFactory

---

src/TemplatedErrorHandler.php
test/TemplatedErrorHandlerTest.php

If it isn't, we can end up with the error or 404 templated contents appending previous contents of the response body, leading to unexpected output.
Fixes #347

Ensure a new stream is used for templated contents

---

src/Application.php
test/IntegrationTest.php

Handlers are not popped correctly in `__invoke()`:
`$handler` from `swallowDeprecationNotices()` is still active after running the application which again swallows all errors after `Zend\Expressive\Application` finished execution.
The modified test passes for this commit, but it does not in the previous (but it should).
Edit: Would it be desired to also open a corresponding issue?

Register only one error handler in `swallowDeprecationNotices()`

---

composer.json
composer.lock
doc/book/features/middleware/implicit-methods-middleware.md
doc/book/reference/migration/to-v1-1.md
doc/book/reference/migration/to-v1.1.md
mkdocs.yml
src/Middleware/ImplicitHeadMiddleware.php
src/Middleware/ImplicitOptionsMiddleware.php
test/Middleware/ImplicitHeadMiddlewareTest.php
test/Middleware/ImplicitOptionsMiddlewareTest.php
test/RouteMiddlewareTest.php

Updates zend-expressive-router dependency to 1.3.2+, and related new versions of router implementations to those supporting that version.
This patch also introduces two new classes, `Zend\Expressive\Middleware\ImplicitHeadMiddleware` and `ImplicitOptionsMiddleware`. These can be placed after the routing middleware, but before the dispatch middleware, in order to handle HEAD and OPTIONS requests when the matched `Route` does not explicitly support them. In each case, they trigger only when:
- the method is the one they are specifically interested in;
- the request composes a `RouteResult` attribute;
- the `RouteResult` composes a `Route` instance (per the changes in zend-expressive-router and the various implementations);
- the `Route` instance indicates that the method is only supported …

Allow HEAD and OPTIONS requests for any matched route

---

.docheader
src/Application.php
src/Exception/MissingDependencyException.php
test/RouteMiddlewareTest.php
test/WhoopsErrorHandlerTest.php

As reported in #419, when using zend-stratigility 1.3 with Expressive 1.0, 405 errors are also now accompanied by deprecation notices. Since this is default functionality, we need to swallow those deprecation notices for now.

Do not emit deprecation notices for 405 errors

---

doc/book/features/router/fast-route.md

Hello @weierophinney,
a few quick considerations that came to my mind (under the influence of the flu)
1. I am not a native english speaker....so please ... have mercy :-)...no, really, pls edit, edit....
...maybe I was over naive in some explainations.
2. Should we add a short intro about what fast-route dispatch data is, how fast.route caching works?
3. Would you prefer to have the class constant suggested by @Ocramius as the config keys?
namely `FastRouteRouter::CONFIG_CACHE_ENABLED` and `FastRouteRouter::CONFIG_CACHE_FILE`
4. I used the default `cache_file` option value to be (both in the config file and in the router class)  `'data/cache/fastroute.php.cache'`. I use to prefix cache files with `php.cache` for php-array/serialized array, `json.cache` for json array/serialized data etc …

fast-route caching doc draft

---

composer.json
composer.lock
src/Application.php
test/ApplicationTest.php
test/RouteMiddlewareTest.php

Updated the depedency on zend-expressive-router to `^2.0`, and, in development, each router implementation to that same constraint.
Doing so has an intersting side-effect: the route result is guaranteed to have valid middleware composed, as the result is created from a `Route` instance, which will raise an exception much earlier in cases of invalid middleware being passed during its own instantiation. This allowed removing two unit tests, as well as a conditional within `dispatchMiddleware()` for verifying we have callable middleware.

Updated to zend-expressive-router 2.0

---

src/Application.php
test/ApplicationTest.php

Provides implementation for #421

Add getter to retrieve configured routes #421

---

composer.json
composer.lock
src/Application.php
src/Container/Exception/InvalidArgumentException.php
src/Container/Exception/NotFoundException.php
src/Container/TemplatedErrorHandlerFactory.php
src/Container/WhoopsErrorHandlerFactory.php
src/ErrorMiddlewarePipe.php
src/TemplatedErrorHandler.php
src/WhoopsErrorHandler.php

This patch marks a number of methods and classes as deprecated for an upcoming 1.1.0 version, based on features proposed in #428. These include:
- `Application::pipeErrorHandler()`
- `Application::routeMiddleware()`
- `Application::dispatchMiddleware()`
- `Application::getFinalHandler()` (this patch provides `getDefaultDelegate()` as a forwards-compatibility measure)
- `Container\InvalidArgumentException`
- `Container\NotFoundException`
- `Container\TemplatedErrorHandlerFactory`
- `Container\WhoopsErrorHandlerFactory`
- `ErrorMiddlewarePipe`
- `TemplatedErrorHandler`
- `WhoopsErrorHandler`
Do *not* merge until #428 is accepted to develop.

Mark deprecated functionality

---

composer.json
composer.lock
test/ApplicationTest.php
test/RouteMiddlewareTest.php
test/RouteResultTrait.php

Please see #434.
It is possible to use version 2.0 of libraries:
- zend-expressive-aurarouter
- zend-expressive-fastroute
- zend-expressive-zendrouter

Allow expressive-router ^2.0 as well as ^1.1 (Expressive 1.1)

---

doc/book/index.md
doc/book/why-expressive.md

This PR: 
- Adds a section to the documentation on when to choose Zend\Expressive
over Zend\Mvc
I'm creating this PR after participating in the discussion on issue #283, _"When to choose Zend\Expressive over Zend\Mvc"_. After providing my feedback, @weierophinney asked me to take what I'd written and add it to the Zend\Expressive and Zend\Mvc docs. This commit adds said revised version of my feedback, to the docs.

Add a section on when to choose Zend\Expressive over Zend\Mvc

---

doc/book/reference/expressive-projects.md

This PR adds the [zimuel.it](http://www.zimuel.it) web site in the expressive project list under *Personal Sites* section of `reference/expressive-projects.md`.

Added zimuel.it in expressive project list

---

src/Container/WhoopsFactory.php
test/Container/WhoopsFactoryTest.php

Currently, when you explicitly set the flags to false, it behaves as if it were true.

Respect JsonResponseHandler flags when false

---

src/Application.php
src/IsCallableInteropMiddlewareTrait.php
test/Application/ConfigInjectionTest.php
test/Container/ApplicationFactoryTest.php
test/Container/ErrorResponseGeneratorFactoryTest.php
test/Router/IntegrationTest.php

- fixed indents
- parenthesis on instantiating a new class
- fixed PHPDocs
- added type hinting

CS fixes (v2.0)

---

src/Container/ApplicationFactory.php
test/Container/ApplicationFactoryIntegrationTest.php

Configuration passed into `ApplicationFactory::injectRoutesAndPipeline()` can be `ArrayObject` or `array`
Resolves #446

#446 hotfix - Arg 2 of ApplicationFactory::injectRoutesAndPipeline() 

---

doc/book/cookbook/autowiring-routes-and-pipelines.md
mkdocs.yml

Per discussion on zendframework/zend-expressive-skeleton#129, we need to cover how to autowire routing definitions, and, optionally, pipeline middleware, when using the programmatic approach. The solution is delegator factories.

Adds a cookbook entry covering autowiring of routes and pipeline middleware

---

.travis.yml
composer.lock

Right now, because PHPUnit 6 only works against PHP 7, we need to keep PHPUnit 5.X versions in the `composer.lock`. This is problematic when contributors do an update while running PHP 7 and then push the updated `composer.lock`.
What this patch does is:
- Update to PHP 7-versions of PHPUnit libraries.
- Updates `.travis.yml` to update those libraries when running under PHP 5.6, forcing installation of the PHPUnit 5.7 variants. This then also _installs_ locked dependencies.

Use PHP 7 deps in `composer.lock`

---

.travis.yml

Instead of listing all dependent packages which needs update
run composer update with flag `--with-dependencies`.

Update travis configuration - intall PHPUnit on PHP5.6 with dependencies

---

src/MarshalMiddlewareTrait.php
src/Middleware/DispatchMiddleware.php
test/Application/MarshalMiddlewareTraitTest.php
test/Middleware/DispatchMiddlewareTest.php

Because `Zend\Expressive\Router\Route` is lenient in the middleware it composes, we cannot assume that the middleware composed is valid http-interop middleware in the dispatcher. As such, this patch does the following:
- Updates `DispatchMiddleware` to compose a router, response prototype, and container, as all are necessary for preparing interop middleware shims.
- Updates `DispatchMiddleware::process` to check if the middleware received is http-interop compatible; if not, it delegates to `MarshalMiddlewareTrait::prepareMiddleware()` to cast it to interop middleware.
This patch supercedes the approach from #454, and fixes #453.

Allow DispatchMiddleware to handle callables and service names

---

doc/book/features/container/delegator-factories.md
doc/book/features/error-handling.md
doc/book/features/helpers/url-helper.md
doc/book/features/router/interface.md
doc/book/features/template/twig.md
doc/book/features/template/zend-view.md
doc/book/getting-started/skeleton.md
doc/book/getting-started/standalone.md
doc/book/index.html
doc/book/reference/cli-tooling.md
doc/book/reference/migration/to-v2.md
mkdocs.yml

This patch builds on #456.
> Create new tutorials based on new skeleton, and mark old tutorials as deprecated.

Document Expressive v2 changes

---

src/Middleware/WhoopsErrorResponseGenerator.php
test/Middleware/WhoopsErrorResponseGeneratorTest.php

Change header from `text/html` to `application/json`

Fix #463 Wrong Whoops JsonResponseHandler Header

---

doc/book/getting-started/skeleton.md

Fixed markdown typo (docs)

---

doc/book/cookbook/autowiring-routes-and-pipelines.md
doc/book/features/application.md
doc/book/features/helpers/url-helper.md
doc/book/features/modular-applications.md
doc/book/reference/migration/to-v2.md

More infos: https://github.com/waylan/Python-Markdown/issues/451

Fixes indentation for nested lists in documentation

---

src/MarshalMiddlewareTrait.php
test/Application/MarshalMiddlewareTraitTest.php
test/IntegrationTest.php
test/TestAsset/CallableInteropMiddleware.php

When using invokable, class-based, duck-typed interop middleware that **NOT** composed in the DI container, `MarshalMiddlewareTrait::marshalInvokableMiddleware` was incorrectly wrapping this in a `CallableMiddlewareWrapper` instead of a `CallableInteropMiddlewareWrapper`; when such middleware was invoked, it was thus incorrectly being passed a response instead of a delegate, leading to a fatal error.
This patch adds a unit test to validate usage, and fixes an incorrect test in the process.
Fixes an issue reported by @robertbasic.

Ensure invokable, duck-typed, class-based interop middleware works

---

src/Middleware/WhoopsErrorResponseGenerator.php
test/Middleware/WhoopsErrorResponseGeneratorTest.php

Add response status code for the Whoops error handler

---

doc/book/features/helpers/url-helper.md

Correct a typo on the documentation for url-helper

Typo fix on url-helper documentation

---

src/Middleware/WhoopsErrorResponseGenerator.php

PSR states
```
* Retrieves data related to the incoming request environment,
* typically derived from PHP's $_SERVER superglobal. The data IS NOT
* REQUIRED to originate from $_SERVER.
```
Nothing suggests that `SCRIPT_NAME` will always exist. Therefore I've added a `isset()` guard and left the default as an empty string.

fix(WhoopsError): ensure the SCRIPT_NAME is set before attempting to use it

---

src/Container/NotFoundDelegateFactory.php
src/Delegate/NotFoundDelegate.php
test/Container/NotFoundDelegateFactoryTest.php
test/Delegate/NotFoundDelegateTest.php

This is a better implementation for chaning the layout of error pages. See also the issue: #360 
I hope my pull request will be accepted :-)

Added custom layout support in NotFoundDelegate

---

composer.json
composer.lock
src/Application.php
src/Delegate/NotFoundDelegate.php
src/MarshalMiddlewareTrait.php
src/Middleware/DispatchMiddleware.php
src/Middleware/ImplicitHeadMiddleware.php
src/Middleware/ImplicitOptionsMiddleware.php
src/Middleware/LazyLoadingMiddleware.php
src/Middleware/NotFoundHandler.php
src/Middleware/RouteMiddleware.php
test/Application/MarshalMiddlewareTraitTest.php
test/Application/TestAsset/CallableInteropMiddleware.php
test/Application/TestAsset/InteropMiddleware.php
test/ApplicationTest.php
test/Container/ApplicationFactoryTest.php
test/IntegrationTest.php
test/Middleware/DispatchMiddlewareTest.php
test/Middleware/ImplicitHeadMiddlewareTest.php
test/Middleware/ImplicitOptionsMiddlewareTest.php
test/Middleware/LazyLoadingMiddlewareTest.php
test/Middleware/NotFoundHandlerTest.php
test/Middleware/RouteMiddlewareTest.php
test/Router/IntegrationTest.php
test/TestAsset/CallableInteropMiddleware.php
test/TestAsset/InteropMiddleware.php

We accomplish it by using `webimpress/http-middleware-compatibility` library
which allows us to use any version of http-interop middleware.
Consumer of the library can decide what version want to use.
In composer.lock we keep `http-interop/http-middleware` in version 0.4.1
so tests run with the following version of middleware:
- lowest: 0.1.1
- locked: 0.4.1
- latest: 0.5.0
The question is if we want to support http-interop/http-middleware in version 0.1.1. This requires method `next` in `NotFoundHandler` (as a proxy to handle method). Method `process` is also now a proxy to `handle` method.
- https://github.com/zendframework/zend-expressive-router/pull/36
- https://github.com/zendframework/zend-stratigility/pull/112
to be merged and released before.

Added support for http-interop/http-middleware 0.5.0 (no BC Break)

---

composer.json

Since the newest versions of zend-stratigility and zend-expressive-router each now depend on webimpress/http-middleware-compatibility, http-interop/http-middleware is no longer a required package. As such, new installations fail, as this package is necessary in order to run Expressive.
This patch adds the package with a constraint of ^0.4.1 in order to fix issues on the existing 2.0.X branch.
Fixes #519.

Require http-interop/http-middleware 0.4.1

---

test/Application/MarshalMiddlewareTraitTest.php
test/ApplicationTest.php

@weierophinney here's the test coverage for nested pipelines. It works in almost all cases, except when piping an `[$object, 'string']`. But I've opened for #527 that.

Test coverage for nested pipelines

---

src/IsCallableInteropMiddlewareTrait.php
src/MarshalMiddlewareTrait.php
test/ApplicationTest.php

Provides a new method, `IsCallableInteropMiddlewareTrait::isCallable()`, which runs its argument through `is_callable()`. If the value passes, it then checks to see if it is an array, and, if so, if:
- the first argument is an object or valid class name, AND
- the second argument is a valid method of the first argument.
This is done because `is_callable()` returns a false positive when a two-element array is passed where the first argument is an object and the second a string; the function does not verify that the second element is a valid method of the first.
Fixes #527

Provides more robust is_callable logic

---

composer.json

The zendframework/zend-expressive-template dependency was not yet updated.

Fix zend-expressive-template dev-dependency

---

docs/book/cookbook/setting-locale-depending-routing-parameter.md
src/Container/ApplicationFactory.php
src/Container/RequestHandlerRunnerFactory.php
src/Handler/NotFoundHandler.php
src/Middleware/ErrorResponseGenerator.php
src/Middleware/ImplicitHeadMiddleware.php
src/Middleware/LazyLoadingMiddleware.php
src/MiddlewareContainer.php
src/MiddlewareFactory.php
test/ApplicationTest.php
test/ConfigProviderTest.php
test/Container/ApplicationConfigInjectionDelegatorTest.php
test/Container/EmitterFactoryTest.php
test/Container/RequestHandlerRunnerFactoryTest.php
test/Container/ResponseFactoryTest.php
test/Container/ServerRequestErrorResponseGeneratorFactoryTest.php
test/Middleware/ImplicitHeadMiddlewareTest.php
test/Middleware/LazyLoadingMiddlewareTest.php
test/MiddlewareContainerTest.php
test/MiddlewareFactoryTest.php

Fixes:
- added constants visibility (to `public`)
- removed unnecessary type casting
- removed default property value
- optimized imports

Expressive 3.0 fixes

---

src/Container/ServerRequestFactoryFactory.php
test/Container/ServerRequestFactoryFactoryTest.php

We cannot return just `ServerRequestFactory::fromGlobals` or `[ServerRequestFactory::class, 'fromGlobals']` as not all containers allow vanilla PHP callable services. Instead, we wrap it in an anonymous function here, which is allowed by all containers tested at this time.

Make the ServerRequestFactory service compatible with all containers

---

src/ConfigProvider.php
test/ConfigProviderTest.php

The `ErrorResponseGenerator` service should be in the `Zend\Expressive\Middleware` namespace, not in the `Zend\Stratigility\Middleware` namespace.

Fix import for ErrorResponseGenerator service in ConfigProvider

---

phpunit.xml.dist
src/ConfigProvider.php
src/Container/StreamFactoryFactory.php
test/Container/StreamFactoryFactoryTest.php
test/Container/StreamFactoryFactoryWithoutDiactorosTest.php

The factory was originally intended to return a callable, and not the stream itself. As such, it needs to be renamed to `StreamFactoryFactory`, and wrap its return value in a closure.
The IMPLICIT_HEAD_MIDDLEWARE_STREAM_FACTORY factory entry was updated to refer to the renamed class.
Fixes #552

Rename StreamFactory, and have it return a callable

---

src/ConfigProvider.php
src/constants.php
test/ConfigProviderTest.php

These were defined as invokables in v2, and had no dependency entries.  However, they were referenced in the pipeline. Having an alias for each allows them to now resolve to the correct factories.

Add aliases for v2 `Implicit*Middleware` classes

---

src/Container/ApplicationFactory.php
src/constants.php
test/Container/ApplicationFactoryTest.php

In order to make upgrading from v2 easier, we need to ensure that we use the same service name in the application factory as we use in the bootstrap. Since changing the bootstrap requires manual intervention, using the `Zend\Expressive\ROUTE_MIDDLEWARE` constant will present a simpler upgrade, as it resolves to a string matching the v2 middleware service name.
See https://github.com/zendframework/zend-expressive-skeleton/pull/222#issuecomment-365748178 for more details.

Use the `Zend\Expressive\ROUTE_MIDDLEWARE` to retrieve the path-based routing middleware.

---

src/Container/ApplicationFactory.php
src/constants.php
test/Container/ApplicationFactoryTest.php

This reverts #556.
The reversion is due to the fact that @webimpress has discovered that all supported containers resolve aliases to the target service BEFORE determining if the service has already been created. As such, pulling a service by its alias will retrieve the same instance as pulling it by its canonical name.
As such, we can use the canonical name in the `ApplicationFactory` when retrieving the routing middleware for use with the `Application`.

Revert usage of ROUTE_MIDDLEWARE constant in ApplicationFactory

---

composer.json
composer.lock
phpunit.xml.dist
src/ConfigProvider.php
src/Container/NotFoundHandlerFactory.php
src/Container/RequestHandlerRunnerFactory.php
src/Container/ResponseFactoryFactory.php
src/Handler/NotFoundHandler.php
src/constants.php
test/ConfigProviderTest.php
test/Container/NotFoundHandlerFactoryTest.php
test/Container/RequestHandlerRunnerFactoryTest.php
test/Container/ResponseFactoryFactoryTest.php
test/Container/ResponseFactoryFactoryWithoutDiactorosTest.php
test/Handler/NotFoundHandlerTest.php
test/Router/IntegrationTest.php

Refactors the `ResponseFactory` to be a `ResponseFactoryFactory`. Any class that needs a response instance should compose a `callable` response factory instead, which can then be invoked in order to produce a response. This ensures we generate a new instance every time, and eliminates the need for mapping discrete "virtual" services to the response factory; we can use the same service everywhere.
The name chosen for the `ResponseFactoryFactory` service is the PSR-7 `ResponseInterface`; this allows us to use an existing name instead of a constant evaluating to an arbitrary string name.

Response factories

---

composer.json
composer.lock
test/Container/RequestHandlerRunnerFactoryTest.php

That particular release decorates the various factories in closures in order to provide type-safety - which means we cannot assume that the properties are the same instances as we provide to the constructor. This patch updates the tests to take that into account.

Updates zend-httphandlerrunner dependency to 1.0.1

---

src/Application.php
test/ApplicationTest.php

The `Zend\Stratigility\path()` function require 1st parameter to string, while `$path` can be `array|callable|Psr\Http\Server\MiddlewareInterface|Psr\Http\Server\RequestHandlerInterface|string` with compare to `/` string.

ensure $path to be string on path() call

---

composer.json
composer.lock
src/Container/ErrorHandlerFactory.php
test/Container/ErrorHandlerFactoryTest.php

The major change is that the stratigility `ErrorHandler` now expects a callable response factory as the first argument, and not a response _instance_. This patch updates the `ErrorHandlerFactory` to use the `ResponseInterface` service to seed the first argument, as that service resolves to a callable factory.
Tests are also updated to demosntrate that the response service is required, and that it cannot return an actual response.

Updates to zend-stratigility 3.0.0alpha4

---

CHANGELOG.md
src/ConfigProvider.php
src/Container/RequestHandlerRunnerFactory.php
src/Container/ServerRequestErrorResponseGeneratorFactory.php
src/Middleware/ErrorResponseGenerator.php
src/Response/ErrorResponseGeneratorTrait.php
src/Response/ServerRequestErrorResponseGenerator.php
src/constants.php
test/ConfigProviderTest.php
test/Container/RequestHandlerRunnerFactoryTest.php
test/Container/ServerRequestErrorResponseGeneratorFactoryTest.php
test/Response/ServerRequestErrorResponseGeneratorTest.php

Provide a dedicated service for the server request error response generator
Instead of re-using the existing `ErrorResponseGenerator`, this patch does the following:
- Separates functionality for generating the error response into a trait, `Zend\Expressive\Response\ErrorResponseGeneratorTrait`. The method `prepareTemplatedResponse()` now expects the error, the response, and an array of data to provide to the template.
- Updates `Zend\Expressive\Middleware\ErrorResponseGenerator` to use the new trait.
- Creates a new class, `Zend\Expressive\Response\ServerRequestErrorResponseGenerator`, which expects a response factory, and optionally the debug flag, renderer, and template to render to. It composes the trait, and generates a response on-the-fly to pass to the trait methods.
The …

Provide a dedicated service for server request error response generation

---

src/Exception/InvalidMiddlewareException.php
src/Exception/MissingDependencyException.php
src/MiddlewareContainer.php
test/ExceptionTest.php

Exceptions thrown by MiddlewareContainer implements ContainerExceptionInterface

---

composer.json
composer.lock
test/Router/IntegrationTest.php

These need update after releasing fixes in `Implicit*Middlewares`
See: https://github.com/zendframework/zend-expressive-router/pull/58

Updated to the latest dependencies and fixed integration tests

---

src/ApplicationConfigInjectionTrait.php
test/Application/ConfigInjectionTest.php
test/Container/ApplicationFactoryTest.php
test/Middleware/DispatchMiddlewareTest.php

See: https://discourse.zendframework.com/t/strange-behaviour-of-implicitoptionsmiddleware-with-multiple-route-on-same-path/496
There is more tests failing now, so it needs some improvements...

Fix deprecation notice with zend-expressive-router 2.4 for config driven apps

---

CHANGELOG.md
composer.json
composer.lock
src/Application.php
src/ConfigProvider.php
src/Container/ApplicationFactory.php
test/ApplicationTest.php
test/Container/ApplicationConfigInjectionDelegatorTest.php
test/Container/ApplicationFactoryTest.php
test/Router/IntegrationTest.php

This is a change proposed while updating the documentation for version 3.  Having two routing middleware is confusing, particularly since the `PathBasedRoutingMiddleware` simply provides methods for modifying the state of the the composed router.
zend-expressive-router 3.0.0rc5 updates to rename `PathBasedRoutingMiddleware` to `Zend\Expressive\Router\RouteCollector`, and to no longer extend `RouteMiddleware`. This allows it to do its one job: create and return `Route` instances that are also injected into the composed router.
This patch updates to that version, and modifies `Application` to compose a `RouteCollector` instead of `PathBasedRoutingMiddleware`.
An accompanying change will be made to the skeleton to pipe the `RouteMiddleware` instead of the `PathBasedRoutingMiddleware`.

Have `Application` compose a `RouteCollector` instead of `PathBasedRoutingMiddleware`

---

docs/book/v3/reference/migration.md

See: https://docs.zendframework.com/zend-expressive/v3/reference/migration/#new-features

Fixed link in the docs

---

CHANGELOG.md
src/ConfigProvider.php

Provide a narrative description of what you are trying to accomplish:
In version 2.2.0 The [`DispatchMiddleware::class`](https://github.com/zendframework/zend-expressive/blob/2.2.0/src/ConfigProvider.php#L46-L48) is an invokable, but it also has a factory. The factory is used in [zend-expressive-router](https://github.com/zendframework/zend-expressive-router/blob/2.4.1/src/ConfigProvider.php#L30) and is causing a conflict. The DispatchMiddlewareFactory should be used instead.

Fix DispatchMiddlewareFactory duplicate

---

docs/book/v3/features/middleware-types.md

Reading the new docs - middleware-types.md for v3 references deprecated Interop namespace instead of Psr

Docs update Psr\ instead of Interop\

---

docs/book/v3/cookbook/autowiring-routes-and-pipelines.md
src/Container/ApplicationConfigInjectionDelegator.php
test/Container/ApplicationConfigInjectionDelegatorTest.php

Hello..just a thought...
Preamble: I still prefer configuration driven pipelines and routes for non trivial projects. 
The current implementation searches for a 'name' key inside each defined route spec, but since the name must be unique we could use the routes array keys to define the name of each route. 
I believe this is also a little more readable: 1 line less per route spec and, at least for me, it's easier to search among array-keys.
Anyway, this PR does not impose a new  "unique key as name" spec... it just allows it by using a string key AND omitting the name inside the spec. If a 'name' is still defined inside the spec that would be the one used, so there is no backward incompatibility.
kind regards

allow config-route string key as name

---

docs/book/v3/cookbook/double-pass-middleware.md
mkdocs.yml

Covers the `doublePassMiddleware` function, updating existing factories, writing and using a delegator factory, and a third-party MiddlewareContainer extension.
Based on discussion on the following forum topic: https://discourse.zendframework.com/t/expressive-3-how-do-pipe-and-lazy-load-double-pass-middlware-class/527

Adds recipe detailing how to use double-pass middleware in v3

---

docs/book/v3/features/container/config.md
mkdocs.yml

Per #588 and https://discourse.zendframework.com/t/zend-expressive-3-dependencies-config-format/531, this patch provides a document with the specification for container configuration that implementations MUST support in order to work with Expressive applications.

Provide a specification for container configuration

---

docs/book/v3/getting-started/quick-start.md

The code sample was missing a closing bracket, which could lead to confusing errors and affecting the user experience.
The documentation was missing a closing bracket, which I added

Closing bracket missing in documentation

---

docs/book/v3/features/container/factories.md

See here:
https://docs.zendframework.com/zend-expressive/v3/features/container/factories/#routecollectorfactory
`TwigRendererFactory ` under `RouteCollectorFactory`
P.S. Really appreciate all the work put in. Will try find the time to make pull requests for things I notice

Correct RouteCollectorFactory feature description

---

docs/book/v3/features/container/factories.md

See here:
https://docs.zendframework.com/zend-expressive/v3/features/container/factories/#zendviewrendererfactory
Says "no additional services are required", but then lists a dependency.
I made a separate pull request for this since this case might be a bit more complex. My understanding is that the actual dependency is the `UrlHelper`.
The `ZendViewRendererFactory` comments added some more confusion:
> Requires the Zend\Expressive\Router\RouterInterface service (for creating the UrlHelper instance).
https://github.com/zendframework/zend-expressive-zendviewrenderer/blob/master/src/ZendViewRendererFactory.php
In any case, I think this small change should suffice to relieve most of the confusion.

Correct ZendViewRendererFactory feature description

---

docs/book/v3/features/template/twig.md

Updates the twig configuration example to add the following, which are also available:
- autoescape
- optimizations
- runtime_loaders
- timezone

Updates twig configuration example to match current offering

---

docs/book/v3/reference/cli-tooling.md

Typo: handler instead of action

---

CHANGELOG.md
docs/book/cookbook/injecting-data-into-templates.md
docs/book/v3/cookbook/access-common-data-in-templates.md
mkdocs.yml

As the title says: It adds a cookbook entry for accessing common data in templates.

Add cookbook entry for accessing common data in templates

---

docs/book/v3/cookbook/using-a-base-path.md

* remove information about package stability - both mentioned packages are now stable.
* simplify documentation about installing and configuring `mtymek/blast-base-url` package, since it now supports auto-wiring with `zend-component-installer`.

Update documentation for running Zend Expressive from a subdirectory:

---

docs/book/v3/cookbook/autowiring-routes-and-pipelines.md

There is a wrong key name printed in the documentation. This PR fixes this.

Documentation: Fix configuration key name

---

docs/book/v3/features/container/config.md

Two of the links in the end are a copy-paste of the one above. This commit fixes it.

Update links in documentation

---

docs/book/v2/cookbook/using-zend-form-view-helpers.md

The provided zend-form component config provider can configure the HelperPluginManager in Expressive v2, as in v3.  It is not essential to replace/delegate/extend the HelperPluginManager factory.
Provide a narrative description of what you are trying to accomplish:
Edited existing documentation

Use component provided config providers.

---

docs/book/v3/cookbook/setting-locale-without-routing-parameter.md

[x]  Is this related to documentation?
- the current regex allows `/eng-us/`, I believe only `en`, `eng`, `en-us`, `en-US`, `en_us`, `en_US` (well, i would remove the last 2 as well) should be allowed
- the current regex requires a trailing `/` after the locale, we should allow base paths like `/en`, `/de` as well
- the stripped part length is variable and should be computed from $locale (adding 1 for the root `/` char)
- provide an example for using a default locale from app configuration

improve the "setting-locale w/o" cookbook example

---

src/Container/ApplicationConfigInjectionDelegator.php

This could be considered just as a tiny refactoring / code-style change: no bugs, no new features
1. don't call an `inject*` method with missing/empty related config values
2. check for empty routes in `injectRoutesFromConfig` before checking is_array and running the loop on an empty array (this make more sense if the method is called outside this delegator, which, now, already checks for emptiness before calling it)

individual checks before calling `inject*` methods

---

composer.json
composer.lock

This patch modifies the test requirements to allow zend-diactoros 2.0 when testing.
At this time, tests pass, which means that Expressive is already compatible with Diactoros 2.0.0. As it's not a direct requirement, this is simply a formality.

Support Diactoros 2.0

---

src/MiddlewareContainer.php
test/MiddlewareContainerTest.php

Per #645, `MiddlewareContainer::get()` was incorrectly casting middleware that also implemented `RequestHandlerInterface` to `RequestHandlerMiddleware`. This particularly affected `Zend\Stratigility\MiddlewarePipe` instances, as they implement both interfaces; if the last middleware in a pipeline called on the handler, users would then encounter a "pipeline exhausted" error, because it would be invoked as a handler, and thus have no reference to the application's pipeline.
This change verifies that the request handler does not also implement `MiddlewareInterface` before casting.
Fixes #645

Do not cast request handlers implementing middleware to `RequestHandlerMiddleware`

---

docs/book/v3/features/helpers/template-variable-container.md
docs/book/v3/features/helpers/url-helper.md
docs/book/v3/features/template/plates.md
mkdocs.yml

This patch documents each of:
- `UrlHelper::getRouteResult()`
- The new `TemplateVariableContainer` and associated middleware
- The new `route()` method available via the PlatesRenderer's `UrlExtension`. This required actually documenting the configuration and factory for the PlatesRenderer, as well as the existing extensions.

Document new zend-expressive-helpers features from 5.2 and 5.3

---

docs/book/v3/reference/migration.md

The namespaces provided in the migration document for the `RouteMiddleware` and `DispatchMiddleware` are incorrect.

Namespace inaccuracy

---

docs/book/v3/features/template/twig.md

For reference please see: zendframework/zend-expressive-twigrenderer#53

Added missing documentation about configuration option "auto_reload"

---

docs/book/v3/cookbook/access-common-data-in-templates.md

Fix namespace and flash message attribute, in accordance with [zend-expressive-flash](https://docs.zendframework.com/zend-expressive-flash/messages/).

Fix flash message on "Common Data In Templates" cookbook

---

docs/book/v1/features/container/factories.md
docs/book/v2/features/container/factories.md
docs/book/v3/features/container/factories.md

Provide a narrative description of what you are trying to accomplish:
Listed provided renderers class names were removed in 0.5.0 release and extracted into separate packages.

Fix docs inconsistency listing old provided renderer classes
