zendframework/zend-expressive

- LICENSE.md
- src/AppFactory.php
- src/Application.php
- src/Container/ApplicationFactory.php
- src/Emitter/EmitterStack.php
- src/Exception/ContainerNotRegisteredException.php
- src/Exception/ExceptionInterface.php
- src/Exception/InvalidMiddlewareException.php
- src/Router/Aura.php
- src/Router/FastRoute.php
- src/Router/Route.php
- src/Router/RouteResult.php
- src/Router/RouterInterface.php
- test/AppFactoryTest.php
- test/ApplicationTest.php
- test/Container/ApplicationFactoryTest.php
- test/Emitter/EmitterStackTest.php
- test/RouteMiddlewareTest.php
- test/Router/AuraRouteTest.php
- test/Router/FastRouteTest.php
- test/Router/RouteTest.php
- test/Router/TestAsset/AuraRoute.php
- test/TestAsset/ContainerException.php
- test/TestAsset/InvokableMiddleware.php
- Added LICENSE.md
- Added a file-level docblock to all classes with license and copyright
information.
- Ensured all classes (except exceptions) have a class-level docblock defining
their purpose.
> Added license information and file/class docblocks

- doc/book/router.fast-route.md
- doc/bookdown.json
Provides documentation around creating your FastRoute objects, configuring them, and injecting them into your router instance for zend-expressive. Both programmatic and IoC approaches are detailed.
> Document advanced configuration of FastRoute

- src/Template/ArrayParametersTrait.php
Pretty much, Twig is not the only adapter that is using this :)
> Resolve issue with the template adapter name in exception

- doc/book/container/bookdown.json
- doc/book/container/factories.md
- doc/book/container/intro.md
- doc/book/container/pimple.md
- doc/book/container/zend-servicemanager.md
- doc/book/containers.md
- doc/bookdown.json
- mkdocs.yml
This pull request is intended to document container usage within zend-expressive.
---
- ~~Document configuring aura.di~~
> Document containers

- doc/book/template/bookdown.json
- doc/book/template/interface.md
- doc/book/template/intro.md
- doc/book/template/middleware.md
- doc/book/template/plates.md
- doc/book/template/twig.md
- doc/book/template/zend-view.md
- doc/bookdown.json
- mkdocs.yml
This pull request documents our templating features:
- Details the `TemplateInterface`
- Details injecting and consuming templates from middleware
- Details installing and using Plates
- Details installing and using Twig
- Details installing and using zend-view
> Document templating features

- doc/book/container/bookdown.json
- doc/book/router/aura.md
- doc/book/router/bookdown.json
- doc/book/router/fast-route.md
- doc/book/router/interface.md
- doc/book/router/intro.md
- doc/book/router/piping.md
- doc/book/router/zf2.md
- mkdocs.yml
- Added an intro
- Added a section on the interface and implementing the interface
- Added a section on piping vs routing
- Made all implementation-specific sections consistent within the section, as well as with other sections
> More thorough router documentation

- doc/book/application.md
- doc/book/quick-start.md
- doc/book/usage-examples.md
- doc/bookdown.json
- mkdocs.yml
- Adds a quick start guide (essentially a step-by-step hello world)
- Adds a chapter on the Application class and its API
- Moves the examples to before the cookbook, and removes the Hello World example (as it's now in the quick start)
> Added Quick Start and Application docs

- CONTRIBUTING.md
> Fixes cd parameter after git clone command

- doc/book/container/zend-servicemanager.md
Change `Zend\Expressive\Router\Aura` to `Zend\Expressive\Router\AuraRouter`
> Update Docs with new router class name

- doc/book/usage-examples.md
This is the correct fix originally indicated by #147.
- Use `ServerRequestFactory::fromGlobals()` to create a request, which is passed to `Server::createServerFromRequest()` along with the `$app`.
> Better fix for #147

- .travis.yml
Supersede & close https://github.com/zendframework/zend-expressive/pull/173
> [Travis-CI] Fix composer install

- doc/book/helpers/body-parse.md
- doc/book/helpers/bookdown.json
- mkdocs.yml
Followup to zendframework/zend-expressive-helpers#5
> Added documentation on the BodyParseMiddleware

- test/AppFactoryTest.php
- test/ApplicationTest.php
- test/Container/ApplicationFactoryTest.php
- test/Emitter/EmitterStackTest.php
- test/RouteMiddlewareTest.php
PR for issue https://github.com/zendframework/zend-expressive/issues/245
> Replace class names with ::class references

- src/AppFactory.php
- test/AppFactoryTest.php
- test/ApplicationTest.php
- test/Container/ApplicationFactoryTest.php
- test/Emitter/EmitterStackTest.php
- test/WhoopsErrorHandlerTest.php
Added tests for uncovered methods, bringing coverage to 100%.
> 100% test coverage

- doc/book/helpers/server-url-helper.md
> Update docs to use xtreamwayz\pimple-container-interop

- doc/book/index.html
> Added install instructions into jumbotron

- src/TemplatedErrorHandler.php
- src/WhoopsErrorHandler.php
> Add support for PHP 7 exceptions

- doc/book/features/router/zf2.md
Code example missing class method
> Router ZF2

- doc/book/cookbook/using-routed-middleware-class-as-controller.md
we can remove extends AbstractPage when using trait ActionBasedInvocation
> remove extends AbstractPage when using trait

- src/Application.php
- src/Container/ApplicationFactory.php
- test/ApplicationTest.php
- test/Container/ApplicationFactoryIntegrationTest.php
- test/Container/ApplicationFactoryTest.php
- test/Container/WhoopsFactoryTest.php
- test/Container/WhoopsPageHandlerFactoryTest.php
> Fix: Remove unused imports

- composer.json
As mentioned in #380 These suggestions are already getting suggested by zend-expressive-template and zend-expressive-router.
> Remove unnecessary suggestions

- .gitignore
- .travis.yml
- CONTRIBUTING.md
- composer.json
- composer.lock
- phpcs.xml
Run test over lowest/locked/latest dependencies
Run test over PHP7.1
Switched to `zend-coding-standard`
> Updated travis configuration

- NOTES.md
- doc/book/reference/usage-examples.md
`$response->getBody()->write(...)` instead of `$response->write(...)`
> Documentation fixes

- README.md
It has been removed in 22ec137
/cc @weierophinney
> Remove link to non-existing file NOTES.md

- doc/book/features/middleware/implicit-methods-middleware.md
Please see https://github.com/zendframework/zend-expressive/issues/436
> Docs fix - Implicit Methods Middleware

- .travis.yml
- composer.json
- composer.lock
- Updated dependencies to the latest version
- Updated travis configuration to work with legacy dependencies.
> Updated dependencies and travis configuration

- doc/book/features/container/aura-di.md
- doc/book/features/error-handling.md
- src/Application.php
- src/Container/ApplicationFactory.php
- test/ApplicationTest.php
- test/Container/ApplicationFactoryTest.php
zendframework/zend-expressive#465
> Convert DefaultDelegate::class to string

- doc/book/features/error-handling.md
> Typo fix error-handling.md

- doc/book/cookbook/custom-404-page-handling.md
- doc/book/features/container/aura-di.md
- doc/book/features/container/pimple.md
- doc/book/features/container/zend-servicemanager.md
- doc/book/features/router/aura.md
- doc/book/features/router/fast-route.md
- doc/book/features/router/zf2.md
- doc/book/index.html
- doc/book/reference/usage-examples.md
Actualize Application namespace to App
Replace string classnames to fully qualified names with `::class`
> Update docs to reflect current code and recommendations

- composer.json
- composer.lock
Mocker is finally released - stable 1.0 version!
> Updated Mockery and PHPUnit

- .gitattributes
- /.coveralls.yml
- /.docheader
- /composer.lock
> Added missing entries in .gitattributes

- doc/book/features/helpers/url-helper.md
Fixed a small typo in the documentation
> Fixed Typo

- .travis.yml
- CHANGELOG.md
- composer.json
- composer.lock
- src/Application.php
- src/Delegate/NotFoundDelegate.php
- src/MarshalMiddlewareTrait.php
- src/Middleware/DispatchMiddleware.php
- src/Middleware/ImplicitHeadMiddleware.php
- src/Middleware/ImplicitOptionsMiddleware.php
- src/Middleware/LazyLoadingMiddleware.php
- src/Middleware/NotFoundHandler.php
- src/Middleware/RouteMiddleware.php
- test/Application/MarshalMiddlewareTraitTest.php
- test/Application/TestAsset/CallableInteropMiddleware.php
- test/Application/TestAsset/InteropMiddleware.php
- test/ApplicationTest.php
- test/Container/ApplicationFactoryTest.php
- test/IntegrationTest.php
- test/Middleware/DispatchMiddlewareTest.php
- test/Middleware/ImplicitHeadMiddlewareTest.php
- test/Middleware/ImplicitOptionsMiddlewareTest.php
- test/Middleware/LazyLoadingMiddlewareTest.php
- test/Middleware/NotFoundHandlerTest.php
- test/Middleware/RouteMiddlewareTest.php
- test/Router/IntegrationTest.php
- test/TestAsset/CallableInteropMiddleware.php
- test/TestAsset/InteropMiddleware.php
Revert #517; instead of providing support for http-interop/http-middleware 0.5.0 in the v2 release series, we will stick to 0.4.1, and v3 will upgrade to PSR-15 final.
> Revert "Merge branch 'feature/517' into develop"

- src/AppFactory.php
- src/Application.php
- src/ApplicationConfigInjectionTrait.php
- src/Container/ApplicationFactory.php
- src/Container/ErrorHandlerFactory.php
- src/Container/ErrorResponseGeneratorFactory.php
- src/Container/NotFoundDelegateFactory.php
- src/Container/NotFoundHandlerFactory.php
- src/Container/WhoopsErrorResponseGeneratorFactory.php
- src/Container/WhoopsFactory.php
- src/Container/WhoopsPageHandlerFactory.php
- src/Delegate/NotFoundDelegate.php
- src/Emitter/EmitterStack.php
- src/IsCallableInteropMiddlewareTrait.php
- src/MarshalMiddlewareTrait.php
- src/Middleware/DispatchMiddleware.php
- src/Middleware/ErrorResponseGenerator.php
- src/Middleware/ImplicitHeadMiddleware.php
- src/Middleware/ImplicitOptionsMiddleware.php
- src/Middleware/LazyLoadingMiddleware.php
- src/Middleware/NotFoundHandler.php
- src/Middleware/RouteMiddleware.php
- src/Middleware/WhoopsErrorResponseGenerator.php
As we support PHP 7.1 as minimum we can use new language features - strict types.
> Add missing types

- README.md
- composer.json
- docs/book/features/container/aura-di.md
- docs/book/features/container/pimple.md
Now we have separate repositories which provide configuration for these dependency injection containers and these should be used with expressive applications.
> Updated documentation - Aura.Di and Pimple containers configuration

- src/Container/StreamFactoryFactory.php
> Added missing import in StreamFactoryFactory

- test/ConfigProviderTest.php
> Added tests for fetching services defined in ConfigProvider

- .travis.yml
- composer.json
- composer.lock
- phpstan.neon
- src/Application.php
- src/Handler/NotFoundHandler.php
- src/MiddlewareFactory.php
- src/Response/ErrorResponseGeneratorTrait.php
- src/Response/ServerRequestErrorResponseGenerator.php
Few modifications for fixes detected by phpstan
> Minor fixes detected by phpstan

- .travis.yml
> Adds symfony/debug to legacy deps of PHP 7 env

- composer.json
Provide a narrative description of what you are trying to accomplish:
> set stratigility to ^3alpha4

- docs/book/v3/getting-started/quick-start.md
fix config file reference within the example code for routes
> fix doc typo

- mkdocs.yml
Entries are duplicated:
https://github.com/zendframework/zend-expressive/blob/e5590e20f80a5fa785e90de47a957b7a94ecddf9/mkdocs.yml#L124-L136
> Fixes the page configuration for MkDocs

- docs/book/v3/features/container/zend-servicemanager.md
A quick fix to the documentation, there were some rogue quotation marks which would cause things to crash and burn. Just doing my bit .... 
- [ X ] Is this related to documentation?
Syntax fixes, there was 2 unneeded quotation marks .... doing my bit
> Syntax fixes

- src/Container/WhoopsFactory.php
- src/Middleware/WhoopsErrorResponseGenerator.php
- test/Middleware/WhoopsErrorResponseGeneratorTest.php
> `WhoopsErrorResponseGenerator` change to restore the default output of Whoops

- .travis.yml
- composer.json
- composer.lock
Updated Travis CI configuration to run all tests on PHP 7.3 with lowest/locked/latest dependencies
> Added PHP 7.3 support

- CHANGELOG.md
- phpstan.neon
- src/MiddlewareFactory.php
correction for the @param value.
> Fix typo in the docbloc for the @param value
